# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


b1 = Book.create(title: "Practical Object-Oriented Design in Ruby", author: "Sandi Metz", description: "Practical Object-Oriented Design in Ruby (POODR) is a programmers tale about how to write object-oriented code. It explains object-oriented design (OOD) using realistic, understandable examples.   POODR is a practical, readable introduction to how OOD can lower your costs and improve your applications.", publisher: "Random House", weeks_on_list: 25, rank_this_week: 1)
b2 = Book.create(title: "99 Bottles of OOP", author: "Sandi Metz", description: "Everybody complains about the weather but nobody does anything about it. Likewise, everyone has an opinion about what good code looks like, but those opinions don't help you create it. This book fills that gap. It explains the process of writing good code, and teaches you to achieve beautifully programmed ends by way of extremely practical means. ", publisher: "Random House", weeks_on_list: 95, rank_this_week: 2)
b3 = Book.create(title: "The Little Prince", author: "Antoine de Saint-Exupéry", description: "Few stories are as widely read and as universally cherished by children and adults alike as The Little Prince. Richard Howard's translation of the beloved classic beautifully reflects Saint-Exupéry's unique and gifted style. Howard, an acclaimed poet and one of the preeminent translators of our time, has excelled in bringing the English text as close as possible to the French, in language, style, and most important, spirit. The artwork in this edition has been restored to match in detail and in color Saint-Exupéry's original artwork. Combining Richard Howard's translation with restored original art, this definitive English-language edition of The Little Prince will capture the hearts of readers of all ages.", publisher: "Random House", weeks_on_list: 34, rank_this_week: 3)

Review.create(comment: "Not only is the book 100% on-point, Sandi has an easy writing style with lots of great analogies that drive every point home.", author: "Avdi Grimm", book_id: b1.id)
Review.create(comment: "Finally read POODR. This is, hands down, the most pristine explanation of OO I’ve ever seen. Highly recommended!", author: "Xavier Defrang", book_id: b1.id)

Review.create(comment: "If you believe that clean object design comes from black magic and guru wisdom, and you want to keep believing that, then don’t read this book. But if you’re ready to learn the simple disciplines that consistently result in robust, flexible software designs, this is the book for you.", author: "Avdi Grimm", book_id: b2.id)
Review.create(comment: "This is an astonishing book about OOP and good coding in general. It's great both for people that want to bring back memories but also for newcomers that just learnt coding (although they should certainly read the references that the book provides as well).", author: "Juan Ignacio", book_id: b2.id)

Review.create(comment: "The story of a stranded pilot, an extraordinary little boy, and their remarkable friendship, The Little Prince has become a cherished fable for generations of readers. As enchanting as it is wise, this beloved classic captures the mysteries of the heart and opens us to the meaning of life and the magic of love.", author: "Back Cover", book_id: b3.id)
Review.create(comment: "YA-This new translation into modern English brings a classic tale into sharper focus for today's teens without sacrificing the beauty and simplicity of the author's writing, and the restored artwork has all the charm of the original drawings. What appears to be a simple tale of two lost souls-one, a pilot marooned in the desert next to his ditched plane; the other, a minuscule prince in self-imposed exile from an asteroid so small that he can watch the sunset 44 times a day-reveals itself as something far more complex. What appears to be a fairy tale for children opens like the petals of the Little Prince's flower into a fantasy that has lessons for all of us.", author: "School Library Journal", book_id: b3.id)
